package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager(){
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId(){
        Task task = new Task(42, "Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "Task in wrong place");
        assertEquals(1, task.getId(), "updated task id should be set");
    }

    @Test
    public void testAddTaskWithAndWithoutId(){
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);
        //System.out.println("Test 1 " + task0.getId() + " Test 2 " + task1.getId());
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        //System.out.println("Test 1 " + task0.getId() + " Test 2 " + task1.getId());
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "id of second task in manager should be 2");
    }

    @Test
    public void checkTaskNotChangedAfterAddTask() {
        int id = 1;
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(task1after.getId(), id);
        assertEquals(task1after.getDescription(), description);
        assertEquals(task1after.getStatus(), status);
        assertEquals(task1after.getName(), name);
    }

    @Test
    void epicAndSubtaskLifecycle() {

        Epic epic = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic);

        Subtask subtask = new Subtask("SubTask 1", "Testing subTask", TaskStatus.NEW, epicId);
        Integer subId = manager.addNewSubtask(subtask);
        assertNotNull(subId);


        List<?> epicSubs = manager.getEpicSubtasks(epicId);
        assertTrue(epicSubs.contains(subtask), "subtask id should be in epicSubs");


        manager.deleteSubtask(subId);
        List<?> epicSubsAfter = manager.getEpicSubtasks(epicId);
        assertFalse(epicSubsAfter.contains(subtask), "subtask should be deleted");
    }





    @Test
    void deleteEpicRemovesSubtasks() {

        Epic epic = new Epic("Epic 1", "Testing epic 1");
        int epicId = manager.addNewEpic(epic);
        Subtask subtask = new Subtask("SubTask 1","Testing subTask", TaskStatus.NEW, epicId);

        manager.deleteEpic(epicId);

        assertFalse(manager.getEpics().contains(epic), "epic not deleted");

        assertFalse(manager.getSubtasks().contains(subtask), "subtask not deleted");
    }





    @Test
    void changingTaskIdAfterAddLeadsToInconsistency() {
        Task task = new Task("Mutable", "desc", TaskStatus.NEW);
        int assigned = manager.addNewTask(task);

        assertEquals(assigned, task.getId(), "ID after added same as assigned");


        task.setId(999);

        Task OldTaskId = manager.getTask(assigned); // менеджер по-прежнему хранит объект в map по ключу assigned
        assertEquals(assigned, OldTaskId.getId(), "task ID differences from key");

    }







}
